In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Data Collection

I collected the various cryptocurrencies address from the Google Big Query. This data was open source and upto some extent. The addresses I collected are inputs and output fields from the database and for this problem statement I think this is sufficient to train a classification model.

In [4]:
# Importing our dataset and merging them to combine it into one single dataset

# <<<<<<<<<<<<<<< Bitcoin Data >>>>>>>>>>>>>>>>
btc_data_input = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\input_btc_address.csv')
btc_data_output = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\output_btc_address.csv')

# <<<<<<<<<<<<<<< Ethereum Data >>>>>>>>>>>>>>>>
eth_data1 = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\ethereum_address1.csv')
eth_data2= pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\eth_address2.csv')
eth_data3 = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\eth_address3.csv')

# <<<<<<<<<<<<<<< Dogecoin Data >>>>>>>>>>>>>>>>
doge_data = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\dogecoin_address.csv')

# <<<<<<<<<<<<<<< Dash Data >>>>>>>>>>>>>>>>
dash_data_input = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\dash_address_input.csv')
dash_data_output = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\dash_address_output.csv')

# <<<<<<<<<<<<<<< Litecoin Data >>>>>>>>>>>>>>>>
ltc_data_input = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\ltc_address_input.csv')
ltc_data_output = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\ltc_address_ouput.csv')

# <<<<<<<<<<<<<<< Polygon Data >>>>>>>>>>>>>>>>
polygon_address1 = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\polygon_address1.csv')
polygon_address2 = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\polygon_address2.csv')

# <<<<<<<<<<<<<<< Zilliqa Data >>>>>>>>>>>>>>>>
zilliqa_address = pd.read_csv(r'D:\Computer Programming\Python\ML-Projects\Crypto Classification\zilliqa_address.csv')

In [5]:
# Making the column name same for all the dataset files
btc_data_input.columns = ['Address']
btc_data_output.columns = ['Address']
eth_data1.columns = ['Address']
eth_data2.columns = ['Address']
eth_data3.columns = ['Address']
doge_data.columns = ['Address']
dash_data_input.columns = ['Address']
dash_data_output.columns = ['Address']
ltc_data_input.columns = ['Address']
ltc_data_output.columns = ['Address']
polygon_address1.columns = ['Address']
polygon_address2.columns = ['Address']
zilliqa_address.columns = ['Address']

### labeling the cryptos according to their addresses

In [6]:
# Crypto data labelling
btc_data_input['crypto_name'] = 'Bitcoin'
btc_data_output['crypto_name'] = 'Bitcoin'

# Ethereum data labelling
eth_data1['crypto_name'] = 'Ethereum'
eth_data2['crypto_name'] = 'Ethereum'
eth_data3['crypto_name'] = 'Ethereum'

# Dogecoin data labelling
doge_data['crypto_name'] = 'Dogecoin'

# Dash data labelling
dash_data_input['crypto_name'] = 'Dash'
dash_data_output['crypto_name'] = 'Dash'

# Litecoin data labelling
ltc_data_input['crypto_name'] = 'Litecoin'
ltc_data_output['crypto_name'] = 'Litecoin'

# Polygon data labelling
polygon_address1['crypto_name'] = 'Polygon'
polygon_address2['crypto_name'] = 'Polygon'

# Zilliqa data labelling
zilliqa_address['crypto_name'] = 'Zilliqa'

### Merging all the collected data into one single dataframe

In [7]:
df = pd.concat([btc_data_input, btc_data_output, eth_data1, eth_data2, eth_data3, doge_data, dash_data_input, dash_data_output, ltc_data_input, ltc_data_output, polygon_address1, polygon_address2, zilliqa_address], ignore_index=True)
df.head()

                                Address crypto_name
0  [19PfW28kMoM16uYGpvZcVZx3iGEUP3AHQk]     Bitcoin
1  [1DZQLUB5nYngw52zUoA7AQ1aJ74UXr4nBF]     Bitcoin
2  [19yj1mUuA6nAoCRVvPY7Wo8MmBc9jPJBpo]     Bitcoin
3  [1M3hLovi5JckrEB1SbN5xXKzhqCRQLLtHa]     Bitcoin
4  [1MghixZrbhncwLGWXiP3ZdeDKhzBaJQPKu]     Bitcoin

### Removing the unwanted '[]' brackets

In [8]:
# From the above head of the dataset we can see that the address contains the unnecessary '[]' brackets. We need to remove them

for i in range(len(df)):
    df['Address'][i] = df['Address'][i].replace('[','').replace(']','')

In [9]:
df.head()

                              Address crypto_name
0  19PfW28kMoM16uYGpvZcVZx3iGEUP3AHQk     Bitcoin
1  1DZQLUB5nYngw52zUoA7AQ1aJ74UXr4nBF     Bitcoin
2  19yj1mUuA6nAoCRVvPY7Wo8MmBc9jPJBpo     Bitcoin
3  1M3hLovi5JckrEB1SbN5xXKzhqCRQLLtHa     Bitcoin
4  1MghixZrbhncwLGWXiP3ZdeDKhzBaJQPKu     Bitcoin

Seems good now :)

# Feature Engineering & Data Preprocessing

 While I was researching about the address of different cryptocurrencies, I found that the address of the cryptocurrencies are of different lengths like address of bitcoin usually starts with 1 or 3 and is of length 34, address of ethereum is of length 42 and starts with 0x, address of dogecoin is of length 34 and starts with D, address of dash is of length 34 and starts with X. So, I will be creating a new column 'address_length' which will contain the length of the address and 'address_prefix' which will contain the starting character of the address.

In [10]:
# creating the columns which I mentioned above

df['address_length'] = df['Address'].apply(len)
df['address_prefix'] = df['Address'].str[:2]

In [11]:
df.head()

,Address,crypto_name,address_length,address_prefix
0,19PfW28kMoM16uYGpvZcVZx3iGEUP3AHQk,Bitcoin,34,19
1,1DZQLUB5nYngw52zUoA7AQ1aJ74UXr4nBF,Bitcoin,34,1D
2,19yj1mUuA6nAoCRVvPY7Wo8MmBc9jPJBpo,Bitcoin,34,19
3,1M3hLovi5JckrEB1SbN5xXKzhqCRQLLtHa,Bitcoin,34,1M
4,1MghixZrbhncwLGWXiP3ZdeDKhzBaJQPKu,Bitcoin,34,1M

In [12]:
# Dropping Duplicates

df_without_duplicates = df.drop_duplicates(subset='Address', keep=False).reset_index(drop=True)
df_without_duplicates.head()

,Address,crypto_name,address_length,address_prefix
0,1JedibY1Aepb6CjtiKVMb6h8bhXzgiYSL2,Bitcoin,34,1J
1,1B5ZUUjUXt4MkBUQNgqTzf5S52cMZPVNb,Bitcoin,33,1B
2,15FxFngAdULgovYV1jDy4AHSPsgKCdKWb5,Bitcoin,34,15
3,15DeGazoMk8afbBKmm35DARWgLPgc4T4d2,Bitcoin,34,15
4,1CwzdV2srLLCnf87erExNA4oEURz2AxPY3,Bitcoin,34,1C

In [29]:
df_without_duplicates['Address'].duplicated().sum()

0

In [15]:
le_for_x.classes_

array(['0x', '11', '12', '13', '14', '15', '16', '17', '18', '19', '1A',
       '1B', '1C', '1D', '1E', '1F', '1G', '1H', '1J', '1K', '1L', '1M',
       '1N', '1P', '1Q', '1R', '1U', '1V', '1X', '1Z', '1c', '1d', '1g',
       '1j', '1n', '1p', '1r', '1u', '1x', '31', '32', '33', '34', '35',
       '36', '37', '38', '39', '3A', '3B', '3C', '3D', '3E', '3F', '3G',
       '3H', '3J', '3K', '3L', '3M', '3N', '3P', '3Q', '9u', '9w', '9y',
       '9z', 'A1', 'A3', 'A4', 'A6', 'A7', 'A8', 'A9', 'AA', 'AB', 'AC',
       'AF', 'D5', 'D6', 'D7', 'D8', 'D9', 'DA', 'DB', 'DC', 'DD', 'DE',
       'DF', 'DG', 'DH', 'DJ', 'DK', 'DL', 'DM', 'DN', 'DP', 'DQ', 'DR',
       'DS', 'DT', 'DU', 'LK', 'LL', 'LM', 'LN', 'LP', 'LQ', 'LR', 'LS',
       'LT', 'LU', 'LV', 'LW', 'LX', 'LY', 'LZ', 'La', 'Lb', 'Lc', 'Ld',
       'Le', 'Lf', 'Lg', 'Lh', 'Li', 'M8', 'M9', 'MA', 'MB', 'MC', 'MD',
       'ME', 'MF', 'MG', 'MH', 'MJ', 'MK', 'ML', 'MM', 'MN', 'MP', 'MQ',
       'MR', 'MS', 'MT', 'MU', 'MV', 'MW', 'Xa', 'Xb', 'Xc', 'Xd', 'Xe',
       'Xf', 'Xg', 'Xh', 'Xi', 'Xj', 'Xk', 'Xm', 'Xn', 'Xo', 'Xp', 'Xq',
       'Xr', 'Xs', 'Xt', 'Xu', 'Xv', 'Xw', 'Xx', 'Xy', 'bc', 'no', 'zi'],
      dtype=object)

In [13]:
# For the next feature engineering steps I will be using the 'address_prefix' column. So, I will be converting the 'address_prefix' column to numerical values using the LabelEncoder

from sklearn.preprocessing import LabelEncoder
le_for_x = LabelEncoder()
df_without_duplicates['address_prefix'] = le_for_x.fit_transform(df_without_duplicates['address_prefix'])

# Now, I will be dropping the 'Address' column as it is not required for the further steps
df_without_duplicates.drop('Address', axis=1, inplace=True)

df_without_duplicates.head()

  crypto_name  address_length  address_prefix
0     Bitcoin              34              18
1     Bitcoin              33              11
2     Bitcoin              34               5
3     Bitcoin              34               5
4     Bitcoin              34              12

### Shuffling the dataset

In [14]:
# We need to shuffle the dataset as initially we concatenated the datasets and the data is not shuffled
df_without_duplicates = df_without_duplicates.sample(frac=1).reset_index(drop=True)
df_without_duplicates.head()

  crypto_name  address_length  address_prefix
0    Dogecoin              34              86
1    Ethereum              42               0
2     Bitcoin              34              40
3    Litecoin              51             174
4        Dash              34             169

# Train Test Split and Model Selection

In [25]:
# Train Test Split
from sklearn.model_selection import train_test_split
X = df_without_duplicates.drop('crypto_name', axis=1)
y = df_without_duplicates['crypto_name']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.22, random_state=10)

In [26]:
# Scaling the data

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_scaled = sc.fit_transform(X_train)
X_test_scaled = sc.transform(X_test)

In [34]:
# Now let's decide which model to choose for predicting the crypto's name. 
# For this I'll be creating one function to check the accuracy of each given model

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score

def evaluate_models(models, X_train, y_train, X_test, y_test, y_encoded_train, y_encoded_test):
    """
    Evaluate multiple models on a given dataset.

    Parameters:
    - models: List of tuples containing (model_name, model_instance)
    - X_train, y_train: Training data and labels
    - X_test, y_test: Testing data and labels

    Prints the accuracy for each model on the testing set.
    """
    for name, model in models:
        if name == "XGBoost":
            model.fit(X_train, y_encoded_train)
            y_pred = model.predict(X_test)
            accuracy = accuracy_score(y_encoded_test, y_pred)
            print(f"{name}: Accuracy = {accuracy:.4f}")
        else:
            model.fit(X_train, y_train)
            y_pred = model.predict(X_test)
            accuracy = accuracy_score(y_test, y_pred)
            print(f"{name}: Accuracy = {accuracy:.4f}")

models = [
    ("Random Forest", RandomForestClassifier()),
    ("Gradient Boosting", GradientBoostingClassifier()),
    ("Support Vector Machine", SVC()),
    ("Decision Tree", DecisionTreeClassifier()),
    ("K-Nearest Neighbors", KNeighborsClassifier()),
    ("Gaussian Naive Bayes", GaussianNB()),
    ("Logistic Regression", LogisticRegression(solver='liblinear')),
    ("XGBoost", XGBClassifier()),
]

xgb_encoder = LabelEncoder()
y_encoded_train = xgb_encoder.fit_transform(y_train)
y_encoded_test = xgb_encoder.transform(y_test)

evaluate_models(models, X_train_scaled, y_train, X_test_scaled, y_test, y_encoded_train, y_encoded_test)

Random Forest: Accuracy = 0.7204
Gradient Boosting: Accuracy = 0.7204
Support Vector Machine: Accuracy = 0.7141
Decision Tree: Accuracy = 0.7204
K-Nearest Neighbors: Accuracy = 0.7198
Gaussian Naive Bayes: Accuracy = 0.5781
Logistic Regression: Accuracy = 0.5237
XGBoost: Accuracy = 0.7204

From the above results we can see that the Random Forest, XGBoost and Gradient Boosting algorithms are giving maximum accuracies so, we will try to do hyperparameter tuning on these algorithms and see what gives the best result after tuning them. The reason why I am ignoring Decision Tress as this algorithm has higher possibility of Overfitiing.

# Hyperparameter Tuning

In [35]:
# For hyperparameter tuning I'll be using GridSearchCV
import warnings
warnings.filterwarnings('ignore')
# Random Forest
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [50, 100, 150, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'criterion': ['gini', 'entropy', 'log_loss'],
}

rf = RandomForestClassifier(n_jobs=5)

rfcv = GridSearchCV(rf, param_grid, cv=5, scoring='accuracy', n_jobs=5)
rfcv.fit(X_train_scaled, y_train)
print(f"Random Forest: Best parameters = {rfcv.best_params_}")
print(f"Random Forest: Best accuracy = {rfcv.best_score_:.4f}")

# Gradient Boosting
param_grid = {
    'n_estimators': [50, 100, 150, 200, 300],
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.1, 0.5, 1],
    'loss' : ['log_loss', 'deviance', 'exponential'],
    'criterion': ['friedman_mse', 'squared_error']
}

gb = GradientBoostingClassifier()

gbcv = GridSearchCV(gb, param_grid, cv=5, scoring='accuracy', n_jobs=5)
gbcv.fit(X_train_scaled, y_train)
print(f"Gradient Boosting: Best parameters = {gbcv.best_params_}")
print(f"Gradient Boosting: Best accuracy = {gbcv.best_score_:.4f}")

# XGBoost
param_grid = {
    'n_estimators': [50, 100, 150, 200, 300],
    'max_depth': [3, 5, 7, 9],
    'learning_rate': [0.01, 0.1, 0.5, 1],
}

xgb = XGBClassifier()

xgbcv = GridSearchCV(xgb, param_grid, cv=5, scoring='accuracy', n_jobs=5)
xgbcv.fit(X_train_scaled, y_encoded_train)
print(f"XGBoost: Best parameters = {xgbcv.best_params_}")
print(f"XGBoost: Best accuracy = {xgbcv.best_score_:.4f}")

Random Forest: Best parameters = {'criterion': 'gini', 'max_depth': None, 'n_estimators': 50}
Random Forest: Best accuracy = 0.7194
Gradient Boosting: Best parameters = {'criterion': 'friedman_mse', 'learning_rate': 0.01, 'loss': 'log_loss', 'max_depth': 3, 'n_estimators': 50}
Gradient Boosting: Best accuracy = 0.7194
XGBoost: Best parameters = {'learning_rate': 0.01, 'max_depth': 3, 'n_estimators': 100}
XGBoost: Best accuracy = 0.7194

In [20]:
add = "XrtkFZMUZC9zKTmg4N9ETFyjLsAv4Gnzwh"
address_start = add[:2]
address_encoded = le_for_x.transform([address_start])

All the models are again giving the same accuracy lets again verify using cross validation score and examine the results

In [36]:
from sklearn.model_selection import cross_val_score

models = [
    ("Random Forest", RandomForestClassifier()),
    ("Gradient Boosting", GradientBoostingClassifier()),
    ("XGBoost", XGBClassifier()),
]

for name, model in models:
    if name == "XGBoost":
        scores = cross_val_score(model, X_train, y_encoded_train, cv=10, n_jobs=5)
        print(f"Average Cross-Validation score of xgb: {scores.mean()}")
        print(f"{name} Cross-Validation score of xgb: {scores}")
    else:
        scores = cross_val_score(model, X, y, cv=10)
        print(f"{name} Cross-Validation scores: {scores}")
        print(f"{name} Average Cross-Validation score: {scores.mean()}")

Random Forest Cross-Validation scores: [0.72183588 0.71766342 0.72183588 0.72005571 0.71866295 0.72005571
 0.71866295 0.71866295 0.71866295 0.72144847]
Random Forest Average Cross-Validation score: 0.7197546886925124
Gradient Boosting Cross-Validation scores: [0.72183588 0.71766342 0.72183588 0.72005571 0.71866295 0.72005571
 0.71866295 0.71866295 0.71866295 0.72144847]
Gradient Boosting Average Cross-Validation score: 0.7197546886925124
Average Cross-Validation score of xgb: 0.7193859816653934
XGBoost Cross-Validation score of xgb: [0.71836007 0.7201426  0.71785714 0.71964286 0.72142857 0.71785714
 0.72142857 0.72142857 0.71785714 0.71785714]

From the above final results we can decide that moving with XGBoost will be beneficial. So now we will save models and the scaler and encoders too.

In [37]:
# Saving the model
import pickle

filename = 'crypto_classification_model.pkl'
with open(filename, 'wb') as file:
    pickle.dump(xgbcv, file)

# Saving the LabelEncoder
filename = 'crypto_label_encoder.pkl'
with open(filename, 'wb') as file:
    pickle.dump(le_for_x, file)

# Saving the XGBoost encoder
filename = 'xgboost_encoder.pkl'
with open(filename, 'wb') as file:
    pickle.dump(xgb_encoder, file)

# Saving the StandardScaler
filename = 'crypto_scaler.pkl'
with open(filename, 'wb') as file:
    pickle.dump(sc, file)